git:
  depth: 1

language: java

jdk:
  - openjdk11

env:
  global:
    - secure: bPJcW+/EUwm9yrH5HjiujDjqpxzBTqrlAZV6S+wMsSITXkevISWZpFuqJ4u5pRBmHp8yi59TQYlrpKRWir14sRI5TqzCEWBDyw4C30XPpa+Qbl51th5oJJ3WeiZcNpE6xzaXO3g6PEFOnKE1A1kH5IrZiyNGdOY6U04wDxnl2fQSRwBmTcmA/Yo541UFwO2EqqgItHiPUMy4XRDt1njLeX+i8u1fYVXkGx1E+JntmgZWRBwZjTo6yXfKnGX8Er4oaMdtTPU/vr49IwVPfIO0OoSK0YUPB3o6TQs4EGbfZzXSZw5unZLpfyq4c7U7DIiK6doKTBKjWC9MBQmPwy5/w7gULCC/OsaNoLsHwXASUkmJqAP2fodw4hSvy060S7hsJJWIb1Fzs2eEpA5apefnd5buGu5MtHaZd3Frkuppgax6hg0vg43p90eCpe74EKTDTCtnhO5dYUQfWrod2FqyiWzh/qJWO4QOyKWK3DlFOqgcVr22TWSjE8leiHV1nytPROMkKAUK+Ygyp+awtm6xgIZZNubWyCojmqcaBg7KAgt/JdZah5Xy9l/kbEGhABXJ90RdlwxTC6CHgcM0DasPYsUvYoZWEP5FmsjAMHWnQ2atbO6XdKaRshZwWwV2L/xHmSMbGPsPjnpfzNyc0PH3COgx5z8QpOToKHgJFolxXZ4=
    - secure: O2B84iMz0tM+gtwZWhGFvh6t8uv42/RGo8Pv+l52D5o61L25YCronngSzcMSc6h0J3Nx9KOCP0yXUn0bf73/sJSwlwl28ErtqtUX3fkpwvjWSBi3eD9FwyiHOKI07ysHbeWWhRnH7PhYuYIQjHw3UIMdS+14D2TrAYnVjFtPLYXHwLmE1dA/KZrv2uUjDWIOlOsXMlq5toH/+ISlQM6U0MyF8xxnjTpmNFLJ899jLQgdqbCWC68W0xNeadLEsyc8RW3hDHJ+YiV6xUyRjorMj3/g6W4Eg7owh0pjvCNsXwOPtExeqU5LmPt0FHCWmxqkEX1EP3M81EfK6mZtMSxTn/tws8qVNlVNjtf0HvxG+09SaesLcY64B4qcb9ljF8LqeH+C1RCbEanRpiOZKgfr/wGAQynNWllRK/TLPTozOEZIF/wcRUhAISgRxJYjwVsjG1xNHb94/G7TUgkoYbZY5Qfl7nEaJz54eZkdt8MjLzc42WndlNCBDCaZyhGGjBysDfGKZKvOQ3y/GQC6lkArDZ7uflC/vy3qqhS2L8VQL5n+4xnX0vF7eMvoB+KZagj/nmDwgcrmiQMiDDdvsyiX4UIvc9kvxHqujhTkbVrX7D+ptnWqMJCyE7bgwypIh1w0Vb6qtcyoFwlUhw/M14eefjM7Oms39rVKUesbcAgJiR4=

before_script: cd build

script:
  - ant clean
  - ant test

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
