git:
  depth: 1

language: java

jdk:
  - openjdk11

before_script: cd build

script:
- ant clean
- ant test
- bash deploy.sh

before_deploy: cd build

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
